feature: add skip role detection CLI flag
thegeeklab/ansible-doctor pull request #134
Opened 2021-07-26 10:25 UTC by ptomas-adacis

I ran some tests but it is possible that I forgot something.

2021-07-26 18:51 UTC, xoxys requested changes
Thanks for your contribution. Just a few small things to change :)

2021-07-26 18:51 UTC, xoxys commented on ansibledoctor/cli.py
> +            "-s",
Lets use `-n`

2021-07-26 18:51 UTC, xoxys commented on ansibledoctor/cli.py
> +            "--skip-role-detection",
According to `-n` I  would like to rename the flag/variables to `--no-role-detection`

2021-07-26 18:51 UTC, xoxys commented on ansibledoctor/doc_parser.py
> +        if not self.config.config["skip_role_detection"]:
That's not required. The entire function is not used at the moment.

2021-07-26 18:51 UTC, xoxys commented on ansibledoctor/doc_parser.py
> +
You added some white spaces in this line, that's why the CI is complaining :)

2021-07-27 06:55 UTC, ptomas-adacis commented
Thank you for your checking

2021-07-27 12:08 UTC, closed without merging

2021-07-27 12:13 UTC, xoxys commented
What happened? Why have you closed it now?

2021-07-27 12:18 UTC, ptomas-adacis commented
Nothing wrong, I did not know that renaming my pull request will cause this closure. I created a new pull request.